# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "public/"
  # This will be your default build command
  command = "yarn build"
  # This is where we will look for your lambda functionsRaw
  functions = "functions/"